// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiHomework.DataAccessLayer;

namespace WebApiHomework.DataAccessLayer.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiHomework.DataAccessLayer.Models.BookEntity", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsHardBook")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("int");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<int>("RecommendedAge")
                        .HasColumnType("int");

                    b.Property<int>("StockNumber")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.ToTable("BookEntities");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "R.L. Stein",
                            IsHardBook = false,
                            Name = "Ghoosebumps",
                            NumberOfPages = 0,
                            PublishedYear = 0,
                            RecommendedAge = 0,
                            StockNumber = 0
                        },
                        new
                        {
                            BookId = 2,
                            Author = "G.R. Martin",
                            IsHardBook = false,
                            Name = "Game of thrones",
                            NumberOfPages = 0,
                            PublishedYear = 0,
                            RecommendedAge = 0,
                            StockNumber = 0
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Homer",
                            IsHardBook = false,
                            Name = "Iliada",
                            NumberOfPages = 0,
                            PublishedYear = 0,
                            RecommendedAge = 0,
                            StockNumber = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
